services:
  registry:
    image: registry:2.8.2
    ports:
      - 5000:5000
    container_name: registry
    environment:
      REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /var/lib/registry
      REGISTRY_STORAGE_DELETE_ENABLED: 'true'
      REGISTRY_HTTP_HEADERS_Access-Control-Allow-Origin: '[http://172.16.21.52:8083]'
      REGISTRY_HTTP_HEADERS_Access-Control-Allow-Methods: '[HEAD,GET,OPTIONS,DELETE]'
      REGISTRY_HTTP_HEADERS_Access-Control-Allow-Credentials: '[true]'
      REGISTRY_HTTP_HEADERS_Access-Control-Allow-Headers: '[Authorization,Accept,Cache-Control]'
      REGISTRY_HTTP_HEADERS_Access-Control-Expose-Headers: '[Docker-Content-Digest]'
      REGISTRY_AUTH: htpasswd
      REGISTRY_AUTH_HTPASSWD_PATH: /auth/htpasswd
      REGISTRY_AUTH_HTPASSWD_REALM: Registry Realm
    volumes:
      - ./auth:/auth
      - ./registry-data:/var/lib/registry

  registry-ui:
    image: joxit/docker-registry-ui:latest
    ports:
      - 8083:80
    container_name: registry-ui
    environment:
      - REGISTRY_TITLE=Docker Registry - Poder Judicial de Río Negro
      - REGISTRY_URL=http://172.16.21.52:5000
      - SINGLE_REGISTRY=true
    depends_on:
      - registry
networks:
  default:
    ipam:
      driver: default
      config:
        - subnet: 192.168.23.0/29
          gateway: 192.168.23.1
