services:
  git:
    image: gitea/gitea:latest
    container_name: git
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - DB_TYPE=sqlite3
    volumes:
      - ./git:/data
    ports:
      - "8080:3000"
      - "22001:22"
    restart: always
networks:
  default:
    ipam:
      driver: default
      config:
        - subnet: 192.168.20.0/29
          gateway: 192.168.20.1
