services:
    cadvisor:
        restart: always
        image: gcr.io/cadvisor/cadvisor
        container_name: cadvisor
        ipc: private
        shm_size: 128M
        networks:
          - network-devops
        ports:
          - "8090:8080"
        volumes:
            - /:/rootfs:ro
            - /var/run:/var/run:rw
            - /sys:/sys:ro
            - /var/lib/docker/:/var/lib/docker:ro
            - /dev/disk/:/dev/disk:ro
            #- /zpool2/docker_config/dns/resolv.conf:/etc/resolv.conf
            #- /zpool2/docker_config/cache/01proxy:/etc/apt/apt.conf.d/01proxy
networks:
  network-devops:
    external: true
