services:
  jenkins:
    #image: jenkins/jenkins:alpine3.20-jdk21
    image: 172.16.21.52:5000/rgeoffroy/jenkins-docker:lts-jdk21-v2
    restart: always
    privileged: true
    user: root
    ports:
      - 8081:8080
      - 50000:50000
    container_name: jenkins
    environment:
      - TZ=America/Argentina/Buenos_Aires
    volumes:
      - ./jenkins_compose/jenkins_configuration:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
networks:
  default:
    ipam:
      driver: default
      config:
        - subnet: 192.168.21.0/29
          gateway: 192.168.21.1
