services:
  jenkins:
    image: jenkins/jenkins:alpine3.20-jdk21
    restart: always
    privileged: true
    user: root
    ports:
      - 8085:8080
      - 50000:50000
    container_name: jenkins
    volumes:
      - /home/rgeoffroy/jenkins_compose/jenkins_configuration:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
networks:
  default:
    ipam:
      driver: default
      config:
        - subnet: 192.168.20.0/29
          gateway: 192.168.20.1
